import fs from 'fs'
// import { generateEnhancedRobotsTxt } from './seo/robotsEnhanced' // 文件已删除

export function generateRobotsTxt(props) {
  // 在 Vercel 生产环境中跳过文件写入操作
  if (process.env.VERCEL || process.env.NODE_ENV === 'production') {
    console.log('Skipping robots.txt generation in production environment')
    return
  }
  
  // 添加安全检查
  if (!props) {
    console.warn('generateRobotsTxt: props is undefined')
    return
  }
  
  const isEnhanced = false // 禁用增强版，文件已删除
  
  try {
    console.log('Using fallback robots.txt generation...')
    generateFallbackRobotsTxt(props)
  } catch (error) {
    console.warn('robots.txt generation failed:', error)
    // 不抛出错误，避免影响页面渲染
  }
}

// 保留原有的简单版本作为回退
function generateFallbackRobotsTxt(props) {
  // 添加安全检查
  if (!props) {
    console.warn('generateFallbackRobotsTxt: props is undefined')
    return
  }
  
  // 优先使用blog.config.js中的配置
  const { siteConfig } = require('./config')
  const LINK = siteConfig('LINK', 'https://www.shareking.vip', props?.NOTION_CONFIG)
  
  // 确保链接不以斜杠结尾
  const baseUrl = LINK && LINK.endsWith('/') ? LINK.slice(0, -1) : LINK
  
  const content = `# Robots.txt for ${baseUrl}
# Generated by NotionNext

# Allow all web crawlers to access all content
User-agent: *
Allow: /

# Disallow access to admin and private areas
Disallow: /admin/
Disallow: /api/
Disallow: /dashboard/
Disallow: /_next/
Disallow: /static/

# Disallow access to search result pages
Disallow: /search?*
Disallow: /search/*

# Allow access to important directories
Allow: /images/
Allow: /css/
Allow: /js/
Allow: /fonts/

# Specific rules for major search engines
User-agent: Googlebot
Allow: /
Crawl-delay: 1

User-agent: Bingbot
Allow: /
Crawl-delay: 1

User-agent: Baiduspider
Allow: /
Crawl-delay: 2

# Block AI training bots
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /

User-agent: Bytespider
Disallow: /

User-agent: Amazonbot
Disallow: /

User-agent: Applebot-Extended
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: meta-externalagent
Disallow: /

# Block problematic bots
User-agent: AhrefsBot
Disallow: /

User-agent: MJ12bot
Disallow: /

User-agent: DotBot
Disallow: /

User-agent: SemrushBot
Disallow: /

# Host declaration
Host: ${baseUrl.replace('https://', '').replace('http://', '')}

# Sitemap locations
Sitemap: ${baseUrl}/sitemap.xml
Sitemap: ${baseUrl}/sitemap-images.xml
Sitemap: ${baseUrl}/sitemap-pages.xml
Sitemap: ${baseUrl}/sitemap-posts.xml
`
  
  try {
    // 检查是否在只读环境中
    if (process.env.VERCEL || process.env.NODE_ENV === 'production') {
      console.log('Skipping robots.txt file write in production environment')
      return
    }
    
    fs.mkdirSync('./public', { recursive: true })
    fs.writeFileSync('./public/robots.txt', content)
    console.log('✅ Robots.txt generated successfully')
  } catch (error) {
    console.warn('⚠️ Cannot write robots.txt file:', error.message)
    // 在vercel运行环境是只读的，这里会报错；
    // 但在vercel编译阶段、或VPS等其他平台这行代码会成功执行
    // 不抛出错误，避免影响页面渲染
  }
}
