name: SEO自动提交

on:
  # 每天UTC时间18:00 (北京时间02:00) 运行
  schedule:
    - cron: '0 18 * * *'
  
  # 手动触发
  workflow_dispatch:
  
  # 当有新内容推送时触发
  push:
    branches: [ main ]
    paths:
      - 'pages/**'
      - 'public/**'
      - 'blog.config.js'

jobs:
  submit-to-search-engines:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 安装依赖
      run: |
        npm install googleapis node-fetch node-cron
    
    - name: 提交到Google
      env:
        GOOGLE_INDEXING_API_KEY: ${{ secrets.GOOGLE_INDEXING_API_KEY }}
      run: |
        node scripts/submit-to-google.js
    
    - name: 上传提交报告
      uses: actions/upload-artifact@v3
      with:
        name: submission-report
        path: google-submission-report.json
        retention-days: 30