name: URL 自动提交

on:
  # 每2小时运行一次
  schedule:
    - cron: '0 */2 * * *'
  
  # 支持手动触发
  workflow_dispatch:

jobs:
  submit:
    name: 提交新 URL
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm install --production
      
      - name: 恢复缓存
        uses: actions/cache@v3
        with:
          path: .cache
          key: url-cache-${{ hashFiles('config/search-engine-submission.json') }}
          restore-keys: url-cache-
      
      - name: 提交 URL
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: npm run submit-urls
      
      - name: 保存缓存
        if: always()
        uses: actions/cache/save@v3
        with:
          path: .cache
          key: url-cache-${{ hashFiles('config/search-engine-submission.json') }}-${{ github.run_id }}